PACKAGE_IMPORT_NAMES = {
    'accelerate': ['accelerate'],
    'beautifulsoup4': ['bs4'],
    'betterproto': ['betterproto'],
    'ctranslate2': ['ctranslate2'],
    'deepl': ['deepl'],
    'diffusers': ['diffusers'],
    'einops': ['einops'],
    'fastapi': ['fastapi'],
    'fugashi': ['fugashi'],
    'gguf': ['gguf'],
    'huggingface-hub': ['huggingface_hub'],
    'httpx': ['httpx'],
    'jaconv': ['jaconv'],
    'mecab-python3': ['MeCab'],
    'msl-loadlib': ['msl'],
    'openai': ['openai'],
    'onnxruntime': ['onnxruntime'],
    'onnxruntime-gpu': ['onnxruntime'],
    'paddleocr': ['paddleocr'],
    'paddlepaddle': ['paddle'],
    'protobuf': ['google.protobuf'],
    'pydantic': ['pydantic'],
    'pyobjc-framework-vision': ['Vision', 'objc'],
    'pyyaml': ['yaml'],
    'safetensors': ['safetensors'],
    'sentencepiece': ['sentencepiece'],
    'torch': ['torch'],
    'torchvision': ['torchvision'],
    'transformers': ['transformers'],
    'translators': ['translators'],
    'ultralytics': ['ultralytics'],
    'unidic-lite': ['unidic_lite'],
    'winsdk': ['winsdk'],
}
